import { useRef } from 'react';
import { MathUtils } from 'three';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { motion } from 'framer-motion-3d';

import { dataStore } from '../../../store/dataStore';
import { laptopMotion } from '../../../utils';

export const Laptop = ({ hinge, elevate, ...props }) => {
  const { nodes, materials } = useGLTF('src/assets/3d/macbook.glb');
  const { laptopOpen, setLaptopHover } = dataStore((state) => ({
    laptopOpen: state.laptopOpen,
    setLaptopHover: state.setLaptopHover,
  }));
  const { start, end } = { start: [22.5, 13, -37], end: [0, 0, -1] };
  const groupRef = useRef();

  useFrame((state) => {
    // const delay = !laptopOpen ? 0.25 : 1;
    state.camera.position.x = MathUtils.lerp(state.camera.position.x, laptopOpen ? end[0] : start[0], 0.075);
    state.camera.position.y = MathUtils.lerp(state.camera.position.y, laptopOpen ? end[1] : start[1], 0.05);
    state.camera.position.z = MathUtils.lerp(state.camera.position.z, laptopOpen ? end[2] : start[2], 0.025);
  });

  // The view was auto-generated by: https://github.com/pmndrs/gltfjsx
  // Events and spring animations were added afterwards
  return (
    <motion.group
      ref={groupRef}
      dispose={null}
      {...props}
      onPointerOver={(e) => (e.stopPropagation(), setLaptopHover(true))}
      onPointerOut={(e) => setLaptopHover(false)}
      {...laptopMotion(laptopOpen).elevate}
    >
      <group position={[0, -0.014, 0]} scale={0.275}>
        <mesh castShadow receiveShadow geometry={nodes.Base_1.geometry} material={materials.Space_Grey} />
        <mesh castShadow receiveShadow geometry={nodes.Base_2.geometry} material={materials.Caps_Lock_Light} />
        <mesh castShadow receiveShadow geometry={nodes.Base_3.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Base_4.geometry} material={materials.Black_Plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Base_5.geometry} material={materials['Keys.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Base_6.geometry} material={materials.Black_Glass} />
        <mesh castShadow receiveShadow geometry={nodes.Base_7.geometry} material={materials['Keys.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Base_8.geometry} material={materials['Touch_Bar_Shot_2021-04-02_at_18.13.28']} />
      </group>
      <motion.group position={[0, 0.008, -0.104]} scale={0.275} {...laptopMotion(laptopOpen).display}>
        <mesh castShadow receiveShadow geometry={nodes.Display_1.geometry} material={materials.Space_Grey} />
        <mesh castShadow receiveShadow geometry={nodes.Display_2.geometry} material={materials['Space_Grey.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Display_3.geometry} material={materials.Black_Glass} />
        <mesh castShadow receiveShadow geometry={nodes.Display_4.geometry} material={materials['Screen OFF']} />
        <mesh castShadow receiveShadow geometry={nodes.Display_5.geometry} material={materials.Black_Plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Display_6.geometry} material={materials.Camera_Light} />
        <mesh castShadow receiveShadow geometry={nodes.Display_7.geometry} material={materials.Glass} />
      </motion.group>
    </motion.group>
  );
};
useGLTF.preload('src/assets/3d/macbook.glb');
