import * as THREE from 'three';
import React, { Suspense, useEffect, useRef, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, useGLTF, ContactShadows, OrbitControls } from '@react-three/drei';
import { useSpring } from '@react-spring/core';
import { a as three } from '@react-spring/three';
import { a as web } from '@react-spring/web';

export const Laptop = ({ open, hinge, ...props }) => {
  const group = useRef();
  // Load model
  const { nodes, materials } = useGLTF('/macbook.glb');
  // Take care of cursor state on hover
  const [hovered, setHovered] = useState(false);
  useEffect(() => void (document.body.style.cursor = hovered ? 'pointer' : 'auto'), [hovered]);
  // Make it float in the air when it's opened
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    // group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, open ? Math.cos(t / 10) / 10 + 0.25 : 0, 0.1)
    // group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, open ? Math.sin(t / 10) / 4 : 0, 0.1)
    // group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, open ? Math.sin(t / 10) / 10 : 0, 0.1)
    // group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, open ? (-2 + Math.sin(t)) / 3 : -4.3, 0.1)
  });
  // The view was auto-generated by: https://github.com/pmndrs/gltfjsx
  // Events and spring animations were added afterwards
  return (
    <group
      ref={group}
      {...props}
      onPointerOver={(e) => (e.stopPropagation(), setHovered(true))}
      onPointerOut={(e) => setHovered(false)}
      dispose={null}
      position={[0, -4, 0]}
    >
      <group position={[0.026, 0.077, -0.831]} rotation={[1.586, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Macbook_1.geometry} material={materials['Body Material']} />
        <mesh castShadow receiveShadow geometry={nodes.Macbook_2.geometry} material={materials['Bezel Material']} />
        <mesh castShadow receiveShadow geometry={nodes.Macbook_3.geometry} material={materials['Keys Material']} />
        <mesh castShadow receiveShadow geometry={nodes.Macbook_4.geometry} material={materials['Keys Light']} />
      </group>
      <three.group position={[0.026, 0.077, -0.811]} rotation-x={hinge}>
        <mesh castShadow receiveShadow geometry={nodes.MacbookDisplay_1.geometry} material={materials['Body Material']} />
        <mesh castShadow receiveShadow geometry={nodes.MacbookDisplay_2.geometry} material={materials['Bezel Material']} />
        <mesh castShadow receiveShadow geometry={nodes.MacbookDisplay_3.geometry} material={materials['Apple Logo']} />
        <mesh castShadow receiveShadow geometry={nodes.MacbookDisplay_4.geometry} material={materials['Camera Lens']} />
        <mesh castShadow receiveShadow geometry={nodes.MacbookDisplay_5.geometry} material={materials['Bezel Material']} />
        <mesh castShadow receiveShadow geometry={nodes.MacbookScreen.geometry} material={materials['Keys Light']} position={[0, 0.005, 0]} />
      </three.group>
    </group>
  );
}
useGLTF.preload('/macbook.glb');
