import {
  getSystemTheme,
  getThemeObject,
  getStoredSettings,
  setStoredSettings,
  getThemeFromStorage,
  saveThemeToStorage,
  isDarkTheme,
  lowerCase,
  rem,
  ProgressbarInstance,
  rgbaToHex,
} from './utils';

import {
  appMotion,
  sceneMotion,
  laptopMotion,
  pageWrapperMotion,
  sectionWrapperMotion,
  sidebarMotion,
  navbarMotion,
  footerMotion,
  heroMotion,
  countersMotion,
  projectsMotion,
  preloaderMotion,
  cardMotion,
  textType,
  textVariant,
  zoomIn,
  fadeIn,
  slideIn,
  staggerContainer,
  staggerContainerMirror,
} from './motion';

export {
  getSystemTheme,
  getThemeObject,
  getStoredSettings,
  setStoredSettings,
  getThemeFromStorage,
  saveThemeToStorage,
  isDarkTheme,
  lowerCase,
  rem,
  ProgressbarInstance,
  rgbaToHex,
  // Motion
  appMotion,
  sceneMotion,
  laptopMotion,
  pageWrapperMotion,
  sectionWrapperMotion,
  sidebarMotion,
  navbarMotion,
  footerMotion,
  heroMotion,
  countersMotion,
  projectsMotion,
  preloaderMotion,
  cardMotion,
  textType,
  textVariant,
  zoomIn,
  fadeIn,
  slideIn,
  staggerContainer,
  staggerContainerMirror,
};
